### ISSUE TITLE
AAPs dont work across layers

### ISSUE THREAD

**Issue by jellejurre** [lyuma/Av3Emulator#115]
In VRChat, AAPs override everything because the parameter is controlled by a curve in the one big controller. In the emulator, this isn't the case because we still have seperate controllers.

**Comment by lyuma** [comment]
Unless VRChat changed something fundamental in the past year, that is not true. VRChat uses the same unity PlayableGraph API that is used in the emulator. That said, changes to layer order or weight, or subtleties in how masking is done as well as how parameters are set could possibly have complex effects on how AAPs behave.

Due to unexplainable Unity weirdness, the emulator does not accurately emulate AAPs unless the "Animator To Debug" dropdown is set to Base.

If you're seeing differences in behavior between the emulator and VRchat, it would be helpful to have an example avatar/controller that demonstrates the problem.

**Comment by jellejurre** [comment]
yeah no, sorry, upon further exploration of the issue, i'm just wrong

thanks for the response, closing the issue
