### ISSUE TITLE
Expression Parameters and AAP controlling same variable

### ISSUE THREAD

**Issue by Hackebein** [lyuma/Av3Emulator#119]
AC3Emulator:
Copies expression parameters into animator even when they are controlled by AAP

VRChat;
Expression parameters doesn't/can't get copied in animators when any AAP is present. Animations doesn't need to play for this behaviour.

**Comment by lyuma** [comment]
What makes you think that the expression parameters are overriding the AAP? It is not possible for anything to override Animated Animator Parameters, and that includes the emulator. If you think it is overriding it, it's likely a visual glitch due to bugs in Unity's Animator window:

By default, Unity only supports showing parametes in the Base layer, and any other layers will be incorrect and show 0 for parameters and layer weights.

In order to see parameters correctly in Unity's Animator window or the Parameters tab, you must select the correct playable in the animator to debug dropdown from av3 emulator, not using the "View Animator" dropdown.
![Default Animator To Debug](https://github.com/lyuma/Av3Emulator/assets/39946030/961acbd4-43b1-471d-a67a-80f22e66711c)

This is a Unity Editor limitation that I do not know of a better workaround for.

**Comment by Hackebein** [comment]
It's not a visual glitch. it's doing it and playing the animation with the overwritten value from expression parameters. I had my Avatar working in Unity in AV3Emulator but it were not working in VRChat until i found out that AAP is causing this.

**Comment by lyuma** [comment]
Would it be possible to share an example avatar that exhibits this issue (you can delete all meshes and materials from it)?

I will still say that your claim entirely contradicts every experience I've had working with AAP, both in the editor and outside.

AAP may be affected by layer and playable weights: that is to say, they could be multiplied by 0.

Additionally, I have observed glitches in the past when Default Animator To Debug is set to anything other than Base. I thought I made accommodations to prevent these glitches, but it's possible a bug still exists here. Please try setting Default Animator To Debug to Base (the default value) and make sure if the AAP issue still happens. This will make it difficult to see it in the animator window, but should ensure accurate execution.

Without a test avatar, I have no way of investigating this other than to say I've never personally observed this issue for myself. So having a test would be much appreciated

**Comment by Hackebein** [comment]
I were stuck on the described behaviour for more than one day. My default Animator for Debug were set to FX.
I can't recreate it anymore. I guess we can close this until somebody can reproduce it?
