### ISSUE TITLE
Contacts Emulation: Contact option "Allow Others" not behaving as intended while "Allow Self" is unchecked

### ISSUE THREAD

**Issue by EasyMochi** [lyuma/Av3Emulator#131]
### Description

Hello!

Contacts set to "Allow Others" while "Allow Self" is unchecked do not behave as expected in play mode

### Reproduction Steps

1. Setup a new contact on an empty gameobject
2. Uncheck "Allow Self" and check "Allow Others"
3. Enter play mode

### Expected Behaviour

The contact should only get triggered by senders outside of the current avatar's hierarchy.

### Actual Behaviour

The contact gets triggered by both senders on the current avatar's hierarchy and outside of it.

### Known Workarounds

None

**Comment by jellejurre** [comment]
I don't think there's much we can do about this, since usually "Allow Others Disabled" contacts get deleted on remote machines and "Allow Self Disabled" contacts get deleted on the local machine, but because we're both in one, we don't get that luxury, and we don't have any control about the internal working of contacts, so while we'd love to implement this, I don't see this happening any time soon.

**Comment by EasyMochi** [comment]
Wouldn't it be possible to disable the contact script at runtime provided we have a way to tell which box is ticked? As a workaround? Because that's pretty much what I'm currently doing~ It is very hacky, though.

**Comment by jellejurre** [comment]
some users might want to test contacts with "allow self" disabled, so this would hinder their workflow
