### ISSUE TITLE
Option to avoid selecting animator controller in project window

### ISSUE THREAD

**Issue by nekobako** [lyuma/Av3Emulator#165]
Hello,

Every time entering play mode using Av3Emulator, the AnimatorController set in `Default Animator To Debug` is selected in the Project window.
When using tools that generates AnimatorController in the Packages folder, it is a little annoying that the Packages folder remains open even after exiting play mode.

I think it would be beneficial to have an option to determine whether the AnimatorController should be selected in the Project window or not.

Environment:
Unity version: 2022.3.6f1
Av3Emulator version: 3.4.3

![av3emu](https://github.com/lyuma/Av3Emulator/assets/4340778/4290b126-e622-4a61-ab01-dd482dab28df)

**Comment by lyuma** [comment]
Good feedback. I actually noticed that too now that you mention it, just kind of didn't think much of it.

Basically the issue is Unity doesn't properly support PlayableGraph in its own animator editor, and by default it will only ever show you the locomotion layer. Selecting the AnimatorController asset is a workaround since Unity seems to use that to determine which layer shows up in the animator controller window.

I wonder if I can temporarily lock all the project windows, select the file, then unlock them. Or maybe I can look at the CsReference and see if there is a private function to do what I need without needing to select the controllers.
