### ISSUE TITLE
'VRCAvatarParameterDriver' does not contain a definition for 'Initialize'

### ISSUE THREAD

**Issue by SevenTies77** [lyuma/Av3Emulator#61]
Assets\Lyuma\Av3Emulator\Scripts\LyumaAv3Runtime.cs(304,34): error CS0117: 'VRCAvatarParameterDriver' does not contain a definition for 'Initialize'

I cannot for the life of my figure out a way around this. I've tried rolling back to previous versions, reinstalling the VRCSDK, Emulator and Gesture Manager. I tried even removing Poiyomi and Pumkins Tools since they cause issues often but that didn't work. I have no other errors in my console besides this one.

**Comment by lyuma** [comment]
that means you're on an old version of AV3 Emulator.

If you are on a new VRCSDK, you need AV3Emulator version 2.9.10.

Try deleting everything in Lyuma/Av3Emulator first, then install av3emulator 2.9.10 again.
You can download it from https://github.com/lyuma/Av3Emulator/releases

**Comment by SevenTies77** [comment]
I was not on an older version. I've literally tried everything.

**Comment by CreamTwinkie** [comment]
Hey, so I was following the procedure of downloading the older version because I was receiving Creator Companion issues, then I downloaded this version, and received the same issues as SevenTies77. I've been spoiled by your awesome emulator, but now I'm afraid it won't work for me. Do you think there is anything I can do to fix it?

This is the console when I import the newest version of the emulator:
![image](https://user-images.githubusercontent.com/115844803/195951397-4cedfa63-f84d-436a-b7f0-66706a0a823c.png)

This is the error when I import the old version as suggested: 
![image](https://user-images.githubusercontent.com/115844803/195951606-19026e92-8f41-4940-b2f0-adb533c73636.png)

I hope it is able to be fixed, because I have gotten used to your brilliant tool! ♥

**Comment by lyuma** [comment]
Please try the latest release 2.9.11, @SevenTies77 and @CreamTwinkie 
When updating, make sure you are also using the *latest* VRCSDK, released on 2022-10-12, 5 days ago.

Thanks for all the reports and testing, and sorry I did not get to this sooner.

I'm going to close this issue. If it's still not working with new SDK and new Av3Emulator, please open a *new* issue with the latest error messages, because it shouldn't be this any more.
