### ISSUE TITLE
OSC does not sync parameters that are not in the regular parameters list

### ISSUE THREAD

**Issue by J-E-Mc** [lyuma/Av3Emulator#62]
Parameters that are not in the avatar's synced parameter list (e.g. Physbone parameters) are not sent over OSC even though they are sent when using the avatar on the VRChat client

https://user-images.githubusercontent.com/44543806/188699616-3269e144-2f96-4172-825c-a3979aebd1ae.mp4

If I add any of these physbone parameters to the parameter list then they are sent over OSC (but this should not be required)

**Comment by lyuma** [comment]
@NotAKidOnSteam also filed this this issue here several months ago: https://github.com/lyuma/Av3Emulator/issues/50
and a PR here: https://github.com/lyuma/Av3Emulator/pull/49 but I didn't quite understand how that PR is supposed to work.

The way it was designed is that Av3Emulator sends all parameters defined in the json file at AppData/LocalLow/VRChat/VRChat/OSC/Avatars/...json
The physbone parameters aren't there by default, but I assume you would need to add them to the json? How are you testing this in VRChat. Are you manually modifying the json file yourself?

I just can't find where it's documented how the PhysBone parameters are supposed to work via OSC.

**Comment by NotAKidOnSteam** [comment]
Pretty sure they are just output, no saving, input, or configuration.

I don't remember but I believe my pr was to allow myself to input OSC directly from VRChat into av3emulator. Needed it to debug some stuff in-game while viewing the animator in-editor.

**Comment by J-E-Mc** [comment]
> @NotAKidOnSteam also filed this this issue here several months ago: #50 and a PR here: #49 but I didn't quite understand how that PR is supposed to work.
> 
> The way it was designed is that Av3Emulator sends all parameters defined in the json file at AppData/LocalLow/VRChat/VRChat/OSC/Avatars/...json The physbone parameters aren't there by default, but I assume you would need to add them to the json? How are you testing this in VRChat. Are you manually modifying the json file yourself?
> 
> I just can't find where it's documented how the PhysBone parameters are supposed to work via OSC.

I tried adding the Physbone parameters to the config file that Av3 uses, it still did not sync them, but they did show up in the list of what should be synced (I copied the definition of another parameter of the same type and then changed the name and path of it)
In VRChat I am simply deleting the OSC configuration file then toggling OSC to force VRChat to regenerate it, that gets VRChat to sync all of the physbone parameters correctly

**Comment by J-E-Mc** [comment]
https://user-images.githubusercontent.com/44543806/188912482-ac13c916-9d75-46ee-8df8-566a7efdb72e.mp4

Here is an example of the issue (sorry for low quality, there is an upload limit of 10 MB)
Switching between 2 Parameter lists, one containing the physbone parameters, one not, no other options are being changed.
the physbone parameters are in the OSC config file that the emulator is using so they should be synced whether they are in the avatar's synced parameter list or not (as that is the behavior of the VRChat client)
