### ISSUE TITLE
OSC value types differ from VRChat with variables controlled by Contacts

### ISSUE THREAD

**Issue by DeltaNeverUsed** [lyuma/Av3Emulator#67]
My setup is
variable X is a bool
Contact A drives X

VRChat would send X as a bool
Av3Emulator would send X as a float

**Comment by lyuma** [comment]
This is not enough detail for me to understand the problem. I'm confused where VRChat is performing the type coercion to bool, and why it's happening.

You say "variable X is a bool". Where did you tell VRChat that X is a bool? Where is X defined? Remember that contact parameters are not supposed to be added to Expression Parameters.

The documentation for contact OnEnter and Constant mode says it will set the value to 0 or 1. Proximity type is clearly a float. None of these types suggest that it is sent as a boolean.

Finally, I'm not actually doing type conversion here. I'm merely forwarding the variable updates sent by the contact receiver. If they are sent over OSC as bool, it is because VRChat is internally setting them as bool variables.

More detail might help me understand the problem. Is there any documentation that says contact receiver parameters should be bool type?

**Comment by DeltaNeverUsed** [comment]
Sorry I wasn't more clear, I only have variable X declared in an animator as a bool, VRChat will convert the float from the contact to the bool of the variable it is assigned to

**Comment by jellejurre** [comment]
I think this is about converting contact floats to animator bools, which is fixed by release 3.0.1.

If not, feel free to reopen and give more context
