### ISSUE TITLE
[Feature] Add support for Booleans and Default Parameter values.

### ISSUE THREAD

**Issue by Provini** [lyuma/Av3Emulator#7]
This new features were added on VRChat on 1/19:
- Boolean support (helpful for toggles)
- Default parameter values via the Expressions Menu

It can be helpful to add support for this in AV3Emulator.

There also some new things like parameter saving and stuff but isn't necessary to emulate.

**Comment by BLANKE1** [comment]
Yeah you can add booleans but manually it seems sadly

**Comment by Provini** [comment]
What do you mean exactly? I switched out my int toggles with booleans and acts the same way.

**Comment by forbiehundie** [comment]
When I changed my int's to bools they're continuing to show up in the emulator as floats instead of bools and will not trigger using the emulated expression menu. I'm still able to test them and the animator by manually adjusting the animator parameters or adding the bools to the emulator menu. The emulated expression menu seems to still be treating them as int's instead of bools.

**Comment by BLANKE1** [comment]
> What do you mean exactly? I switched out my int toggles with booleans and acts the same way.


https://user-images.githubusercontent.com/68296465/105460430-6023d700-5c51-11eb-82b9-b88eb73fe426.mp4
