### ISSUE TITLE
Unable To Drive Animator Parameter

### ISSUE THREAD

**Issue by Kiddo-Kris** [lyuma/Av3Emulator#75]
In some cases, the emulator cannot drive any animator parameter. When the problem occurs, animator parameters will set/locked to false/0/0.0. When parameter changed in the emulator script, the parameters in the animator will set to it for a fraction of second, then set to false/0/0.0 immediatly after.
![O8QH`6AFT~PJOD5_ZE 6}7N](https://user-images.githubusercontent.com/56265123/204734949-d93a9bb5-4149-4502-8a0e-1c85a3e718e1.png)

![EE54(14(L$4`(E9VI@NYIAH](https://user-images.githubusercontent.com/56265123/204734957-a56707e7-f59f-43a5-8924-f2c1b922446a.png)

**Comment by jellejurre** [comment]
I think this is a visual glitch which has to do with the fact that you don't have the "Default animator to debug" set on the AV3 Emulator control.

Especially since the "Set 4 - Misty" is being played in your screenshot, so the implementation works well, just not the visuals because of this setting.

If this isn't the case, feel free to reopen the issue with more information.
